[package]
name = "fourthrail"
version = "0.1.0"
authors = ["MislankaNova <MislankaNova@hotmail.com>"]

[dependencies.pancurses]
version = "0.8"
features = ["wide"]

[lib]
name = "fourthrail"
path = "src/lib.rs"

